version: '3'
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow

  ffmpeg:
    image: nightseas/ffmpeg

  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer_data:/data
    ports:
      - "9000:9000"
        
  airflow:
    image: blinkenosa/docker-airflow
    privileged: true
    restart: always
    depends_on:
      - postgres
      - ffmpeg
    command: webserver
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
      - /var/run/docker.sock:/var/run/docker.sock
      # Directory containing files as input on server:
      - /opt/av_hdd:/opt/av_hdd
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local

      # Airflow settings:
      - AIRFLOW__SMTP__SMTP_HOST=smtp.ceu.edu
      - AIRFLOW__SMTP__SMTP_STARTTLS=False
      - AIRFLOW__SMTP__SMTP_SSL=False
      - AIRFLOW__SMTP__SMTP_PORT=25
      - AIRFLOW__SMTP__SMTP_MAIL_FROM=OSA.Workflow@ceu.edu

      # AMS settings:
      - AMS_API=https://ams.osaarchivum.org/api
      - AMS_API_TOKEN=b3b519040de19c8b5fdc66e319a77ccd779c95a0

      # Environment variables for the osa-av-workflow
      - AV_INPUT_DIR=/opt/av_hdd/videos
      - AV_OUTPUT_DIR=/opt/av_hdd/aip
      - AV_FINAL_DIR=/opt/av_hdd/aip
      - AV_MASTER_FILE_EXTENSION=avi
      - AV_ACCESS_FILE_EXTENSION=mp4
      - AV_BARCODE_PATTERN=^HU_OSA_[0-9]{8}$$
      - AV_STAFF_EMAIL_LIST=bonej@ceu.edu,danij@ceu.edu,krolikowskid@ceu.edu
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
